/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pzhao_opensltest_MainActivity */

#ifndef _Included_com_pzhao_opensltest_MainActivity
#define _Included_com_pzhao_opensltest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    setJniEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pzhao_opensltest_MainActivity_setJniEnv
  (JNIEnv *, jobject);

/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    createEngine
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_pzhao_opensltest_MainActivity_createEngine
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    checkWrite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pzhao_opensltest_MainActivity_checkWrite
  (JNIEnv *, jclass);

/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    write
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pzhao_opensltest_MainActivity_write
  (JNIEnv *, jclass);

/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    createAudioPlayer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pzhao_opensltest_MainActivity_createAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    setPlayingUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_pzhao_opensltest_MainActivity_setPlayingUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    setMuteUriAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_pzhao_opensltest_MainActivity_setMuteUriAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_pzhao_opensltest_MainActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pzhao_opensltest_MainActivity_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
